fail_fast: true
repos:
  - repo: local
    hooks:
      # mypy
      #      - id: mypy
      #        name: mypy
      #        entry: mypy src
      #        language: system
      #        always_run: true
      #        pass_filenames: false
      # black
      - id: black
        name: black
        entry: black --line-length 120 src
        exclude: (Pipfile|.pre-commit-config.yaml|pyproject.toml)
        language: system
        always_run: true
        pass_filenames: true
#      # flake8
#      - id: flake8
#        name: flake8
#        entry: pflake8 src
#        language: system
      #        always_run: true
      #        pass_filenames: false
      #      # darglint
      #      - id: darglint
      #        name: darglint
      #        entry: darglint --docstring-style google --strictness full -v 2 src
      #        language: system
      #        always_run: true
      #        pass_filenames: false
      # pytest
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
